apiVersion: ipam.be.kuid.dev/v1alpha1
kind: IPIndex
metadata:
  name: kubenet.default
  namespace: default
spec:
  prefixes:
  - labels:
      infra.kuid.dev/purpose: loopback
    prefix: 10.0.0.0/24
